#Porject-----------------------------------------------------------
project:
  componentScan: com

#Server------------------------------------------------------------
server:
  port: 8080
  compression:
    enabled: true
  error:
    includeStacktrace: ALWAYS

#Spring------------------------------------------------------------
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, ${spring.autoconfigure.exclude.extension:}
  profiles:
    active: dev
#Jackson-----------------------------------------------------------
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS
    defaultPropertyInclusion: NON_NULL
#Database----------------------------------------------------------
  database:
    showSql: true
    showSqlArg: true
  datasource:
    enabled: false
    borrowConnectionTimeout: 30 #For atomikos
    reapTimeout: 300 #For atomikos
    maintenanceInterval: 60 #For atomikos, connection recycle time
    loginTimeout: 5 #For atomikos, connection pool, wait to get datasource max time
    maxIdleTime: 60 #For atomikos
    idleTimeout: 60000 #For hikari
    maxLifetime: 60000 #For hikari, atomikos
    validationTimeout: 3000 #For hikari
    minPoolSize: 2 #For atomikos
    maxPoolSize: 5 #For atomikos
    maximumPoolSize: 5 #For hikari
    uniqueResourceName: dataSource-${random.uuid} #For atomikos
#Jta---------------------------------------------------------------
  jta:
    atomikos:
      enabled: false
      properties:
        maxActives: 200
        maxTimeout: 0
        defaultJtaTimeout: 3000000
        registered: true
        #Must be config this properties when use multiple application with atomikos
#        logBaseDir =
#        outputDir =
#        consoleFileName =
#        logBaseName =
#Thymeleaf---------------------------------------------------------
  thymeleaf:
    cache: false #Set to false for hot refresh
  web:
    resources:
      staticLocations: classpath:static
      chain:
        strategy:
          content:
            enabled: true
            paths: /**/*.css,/**/*.png,/**/*.js
      cache:
        period: 31536000
#Devtools----------------------------------------------------------
##It must be disable while serialization. otherwise will case problem. Ex: use redis must be disable it!!.
  devtools:
    livereload:
      enabled: true

#I18n--------------------------------------------------------------
i18n:
  messages:
    basename: classpath*:i18n/**
    cacheSeconds: -1
    encoding: UTF-8

#Logging-----------------------------------------------------------
logging:
  level:
    root: WARN
    com.bi: DEBUG
    com.bi.base: WARN
    com.bi.base.ApplicationMain: INFO
    com.bi.base.database.jdbc: INFO
  pattern:
    console: '%clr(%d{yy-MM-dd HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
